/**
 * scripts/sync-version.js
 * Automatically synchronizes the application version across package.json and src/version.ts.
 * Appends '-dev' suffix when on 'develop' (or any non-master) branch, and removes it on 'master'.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function getGitBranch() {
  if (process.env.GIT_BRANCH) return process.env.GIT_BRANCH.replace('refs/heads/', '');
  if (process.env.GITHUB_REF_NAME) return process.env.GITHUB_REF_NAME;
  if (process.env.BRANCH) return process.env.BRANCH;

  try {
    const branch = execSync('git rev-parse --abbrev-ref HEAD', {
      cwd: path.resolve(__dirname, '..'),
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore']
    }).trim();
    return branch || 'master';
  } catch {
    return 'master';
  }
}

function getVersionInfo(pkg) {
  const isTag = process.env.GITHUB_REF_TYPE === 'tag' || (process.env.GITHUB_REF_NAME && /^v\d+\.\d+\.\d+/.test(process.env.GITHUB_REF_NAME));
  const tagRef = process.env.GITHUB_REF_NAME;

  if (isTag && tagRef) {
    const cleanTag = tagRef.replace(/^v/, '');
    const isPrerelease = cleanTag.includes('-');
    const baseVer = cleanTag.split('-')[0];
    return {
      targetVersion: cleanTag,
      baseVersion: baseVer,
      branch: tagRef,
      isDevBuild: isPrerelease,
    };
  }

  const rawVersion = pkg.version || '1.4.4';
  const baseVersion = rawVersion.replace(/-(dev|beta|rc|alpha)(\.\d+)?$/, '');

  const branch = getGitBranch();
  const isMaster = branch === 'master';
  
  let targetVersion = rawVersion;
  if (isMaster) {
    targetVersion = baseVersion;
  } else if (!rawVersion.includes('-beta') && !rawVersion.includes('-rc') && !rawVersion.includes('-alpha')) {
    targetVersion = `${baseVersion}-dev`;
  }

  return {
    targetVersion,
    baseVersion,
    branch,
    isDevBuild: targetVersion.includes('-'),
  };
}

function syncVersion() {
  const pkgPath = path.resolve(__dirname, '../package.json');
  const versionTsPath = path.resolve(__dirname, '../src/version.ts');

  if (!fs.existsSync(pkgPath)) return;

  const pkgRaw = fs.readFileSync(pkgPath, 'utf8');
  const pkg = JSON.parse(pkgRaw);

  const { targetVersion, baseVersion, branch, isDevBuild } = getVersionInfo(pkg);

  // 1. Update package.json if needed
  if (pkg.version !== targetVersion) {
    pkg.version = targetVersion;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
    console.log(`[version-sync] Synchronized package.json version: ${targetVersion} (ref: ${branch})`);
  } else {
    console.log(`[version-sync] package.json version is up to date: ${targetVersion} (ref: ${branch})`);
  }

  // 2. Generate/Update src/version.ts
  const versionTsContent = `/**
 * LuxQMK Studio Version Information
 * Automatically generated by scripts/sync-version.js. DO NOT EDIT DIRECTLY.
 * Base version is managed in package.json.
 */

export const BASE_VERSION = '${baseVersion}';
export const GIT_BRANCH = '${branch}';
export const IS_DEV_BUILD = ${isDevBuild};
export const APP_VERSION = '${targetVersion}';

export default APP_VERSION;
`;

  let existingTs = '';
  if (fs.existsSync(versionTsPath)) {
    existingTs = fs.readFileSync(versionTsPath, 'utf8');
  }

  if (existingTs !== versionTsContent) {
    fs.writeFileSync(versionTsPath, versionTsContent, 'utf8');
    console.log(`[version-sync] Generated src/version.ts with APP_VERSION = "${targetVersion}"`);
  }
}

syncVersion();
