/**
 * scripts/sync-version.js
 * Automatically synchronizes the application version across package.json and src/version.ts.
 * Appends '-dev' suffix when on 'develop' (or any non-master) branch, and removes it on 'master'.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function getGitBranch() {
  if (process.env.GIT_BRANCH) return process.env.GIT_BRANCH.replace('refs/heads/', '');
  if (process.env.GITHUB_REF_NAME) return process.env.GITHUB_REF_NAME;
  if (process.env.BRANCH) return process.env.BRANCH;

  try {
    const branch = execSync('git rev-parse --abbrev-ref HEAD', {
      cwd: path.resolve(__dirname, '..'),
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore']
    }).trim();
    return branch || 'master';
  } catch {
    return 'master';
  }
}

function syncVersion() {
  const pkgPath = path.resolve(__dirname, '../package.json');
  const versionTsPath = path.resolve(__dirname, '../src/version.ts');

  if (!fs.existsSync(pkgPath)) return;

  const pkgRaw = fs.readFileSync(pkgPath, 'utf8');
  const pkg = JSON.parse(pkgRaw);

  const rawVersion = pkg.version || '1.4.1';
  // Strip any existing -dev suffix to obtain pristine base version
  const baseVersion = rawVersion.replace(/-dev(\.\d+)?$/, '');

  const branch = getGitBranch();
  const isMaster = branch === 'master';
  const targetVersion = isMaster ? baseVersion : `${baseVersion}-dev`;

  // 1. Update package.json if needed
  if (pkg.version !== targetVersion) {
    pkg.version = targetVersion;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
    console.log(`[version-sync] Synchronized package.json version: ${targetVersion} (branch: ${branch})`);
  } else {
    console.log(`[version-sync] package.json version is up to date: ${targetVersion} (branch: ${branch})`);
  }

  // 2. Generate/Update src/version.ts
  const versionTsContent = `/**
 * LuxQMK Studio Version Information
 * Automatically generated by scripts/sync-version.js. DO NOT EDIT DIRECTLY.
 * Base version is managed in package.json.
 */

export const BASE_VERSION = '${baseVersion}';
export const GIT_BRANCH = '${branch}';
export const IS_DEV_BUILD = ${!isMaster};
export const APP_VERSION = '${targetVersion}';

export default APP_VERSION;
`;

  let existingTs = '';
  if (fs.existsSync(versionTsPath)) {
    existingTs = fs.readFileSync(versionTsPath, 'utf8');
  }

  if (existingTs !== versionTsContent) {
    fs.writeFileSync(versionTsPath, versionTsContent, 'utf8');
    console.log(`[version-sync] Generated src/version.ts with APP_VERSION = "${targetVersion}"`);
  }
}

syncVersion();
