/**
 * LuxQMK Studio Version Information
 * Automatically generated by scripts/sync-version.js. DO NOT EDIT DIRECTLY.
 * Base version is managed in package.json.
 */

export const BASE_VERSION = '1.4.3';
export const GIT_BRANCH = 'develop';
export const IS_DEV_BUILD = true;
export const APP_VERSION = '1.4.3-dev';

export default APP_VERSION;
